# Generated by Django 5.1.3 on 2024-11-14 21:09

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TIN",
                    models.CharField(
                        max_length=9, validators=[application.models.validate_TIN]
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(default="", max_length=150)),
                (
                    "filing_type",
                    models.CharField(
                        choices=[
                            ("Simple", "Simple"),
                            ("Credits", "Credits"),
                            ("Itemizing", "Itemizing"),
                            ("Sole Proprietor", "Sole Proprietor"),
                            ("Corporation", "Corporation"),
                        ],
                        max_length=100
                    ),
                ),
                (
                    "tax_year",
                    models.SmallIntegerField(
                        default=2024, validators=[application.models.validate_tax_year]
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("Personal Taxes", "Personal Taxes"),
                            ("Corporate Taxes", "Corporate Taxes"),
                            ("Extension", "Extension"),
                            ("Amendment", "Amendment"),
                            ("Withholdings Adjustment", "Withholdings Adjustment"),
                            ("Advisory", "Advisory"),
                            ("Reject Correction", "Reject Correction"),
                        ],
                        default="Personal Taxes",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
