# Generated by Django 5.1.3 on 2024-11-26 06:13

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="TIN",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                validators=[application.models.validate_TIN],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="filing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Simple", "Simple"),
                    ("Credits", "Credits"),
                    ("Itemizing", "Itemizing"),
                    ("Sole Proprietor", "Sole Proprietor"),
                    ("Corporation", "Corporation"),
                ],
                default="",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="product",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Personal Taxes", "Personal Taxes"),
                    ("Corporate Taxes", "Corporate Taxes"),
                    ("Extension", "Extension"),
                    ("Amendment", "Amendment"),
                    ("Withholdings Adjustment", "Withholdings Adjustment"),
                    ("Advisory", "Advisory"),
                    ("Reject Correction", "Reject Correction"),
                ],
                default="Personal Taxes",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="tax_year",
            field=models.SmallIntegerField(
                blank=True,
                default=2024,
                null=True,
                validators=[application.models.validate_tax_year],
            ),
        ),
    ]
